version: "3.7"
services:
  hits:
    image: . 
    depends_on:
     - redis
    networks:
     - homework-3
    ports:
     - 5000:5000  



  redis:
    image: .
    networks:
     - homework-3
    ports:
      - 6379:6379

  
networks:
  homework-3:
    driver: bridge
