---
# tasks file for php
- name: Install php (state=present is optional)
  apt:
    name:{{ item }}
    update_cache:yes
    state:latest 
  with_items:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
    
